import {
  CropBatch,
  SyncRecord,
  SensorReading,
  TemperaturePoint,
  SensorAlert,
  RouteStop,
  Shipment,
  CrateDelivery,
} from './types';

export const mockUser = {
  supplier: {
    id: 'sup-001',
    name: 'Ahmad Razali',
    email: 'ahmad@biolink.my',
    role: 'supplier' as const,
    farmName: 'Ladang Hijau Ahmad',
  },
  driver: {
    id: 'drv-001',
    name: 'Ravi Kumar',
    email: 'ravi@biolink.my',
    role: 'driver' as const,
    vehiclePlate: 'WGT 1234',
  },
};

export const mockBatches: CropBatch[] = [
  {
    id: 'b001',
    batchId: 'BL-2024-0041',
    cropType: 'Lettuce',
    grade: 'A',
    gradeConfidence: 94.2,
    weight: 25.5,
    farmName: 'Ladang Hijau Ahmad',
    date: '2024-01-15',
    status: 'approved',
    syncStatus: 'synced',
    notes: 'Excellent color uniformity, no defects detected',
  },
  {
    id: 'b002',
    batchId: 'BL-2024-0040',
    cropType: 'Cabbage',
    grade: 'A',
    gradeConfidence: 91.8,
    weight: 32.0,
    farmName: 'Ladang Hijau Ahmad',
    date: '2024-01-15',
    status: 'approved',
    syncStatus: 'synced',
    notes: 'Firm heads, vibrant green, no pest damage',
  },
  {
    id: 'b003',
    batchId: 'BL-2024-0039',
    cropType: 'Tomatoes',
    grade: 'B',
    gradeConfidence: 87.3,
    weight: 18.2,
    farmName: 'Ladang Hijau Ahmad',
    date: '2024-01-14',
    status: 'approved',
    syncStatus: 'synced',
    notes: 'Minor surface blemishes, acceptable quality',
  },
  {
    id: 'b004',
    batchId: 'BL-2024-0038',
    cropType: 'Spinach',
    grade: 'A',
    gradeConfidence: 96.1,
    weight: 12.8,
    farmName: 'Ladang Hijau Ahmad',
    date: '2024-01-14',
    status: 'approved',
    syncStatus: 'synced',
    notes: 'Deep green color, fresh aroma, no wilting',
  },
  {
    id: 'b005',
    batchId: 'BL-2024-0037',
    cropType: 'Choy Sum',
    grade: 'B',
    gradeConfidence: 82.5,
    weight: 22.4,
    farmName: 'Ladang Hijau Ahmad',
    date: '2024-01-13',
    status: 'approved',
    syncStatus: 'pending',
    notes: 'Slight yellowing on outer leaves, core quality good',
  },
  {
    id: 'b006',
    batchId: 'BL-2024-0036',
    cropType: 'Broccoli',
    grade: 'C',
    gradeConfidence: 78.9,
    weight: 15.0,
    farmName: 'Ladang Hijau Ahmad',
    date: '2024-01-13',
    status: 'rejected',
    syncStatus: 'synced',
    notes: 'Yellowing detected, overmatured florets',
  },
  {
    id: 'b007',
    batchId: 'BL-2024-0035',
    cropType: 'Carrot',
    grade: 'A',
    gradeConfidence: 93.7,
    weight: 28.6,
    farmName: 'Ladang Hijau Ahmad',
    date: '2024-01-12',
    status: 'approved',
    syncStatus: 'synced',
    notes: 'Uniform size, bright orange, no cracks',
  },
  {
    id: 'b008',
    batchId: 'BL-2024-0034',
    cropType: 'Cucumber',
    grade: 'B',
    gradeConfidence: 85.2,
    weight: 20.1,
    farmName: 'Ladang Hijau Ahmad',
    date: '2024-01-12',
    status: 'pending',
    syncStatus: 'pending',
    notes: 'Mixed sizes, acceptable firmness',
  },
  {
    id: 'b009',
    batchId: 'BL-2024-0033',
    cropType: 'Bok Choy',
    grade: 'A',
    gradeConfidence: 95.0,
    weight: 16.3,
    farmName: 'Ladang Hijau Ahmad',
    date: '2024-01-11',
    status: 'approved',
    syncStatus: 'synced',
    notes: 'Perfect specimen, crisp white stalks',
  },
  {
    id: 'b010',
    batchId: 'BL-2024-0032',
    cropType: 'Sweet Pepper',
    grade: 'B',
    gradeConfidence: 80.4,
    weight: 14.7,
    farmName: 'Ladang Hijau Ahmad',
    date: '2024-01-11',
    status: 'pending',
    syncStatus: 'failed',
    notes: 'Minor shape irregularity, color acceptable',
  },
];

export const mockSyncHistory: SyncRecord[] = [
  {
    id: 'sync-001',
    timestamp: '2024-01-15 14:32',
    status: 'success',
    batchesSynced: 3,
    message: 'All batches uploaded successfully',
  },
  {
    id: 'sync-002',
    timestamp: '2024-01-15 12:15',
    status: 'success',
    batchesSynced: 2,
    message: 'Sync completed',
  },
  {
    id: 'sync-003',
    timestamp: '2024-01-14 18:45',
    status: 'partial',
    batchesSynced: 1,
    message: 'Partial sync — 1 of 2 batches uploaded (low signal)',
  },
  {
    id: 'sync-004',
    timestamp: '2024-01-14 09:20',
    status: 'success',
    batchesSynced: 4,
    message: 'All batches uploaded successfully',
  },
  {
    id: 'sync-005',
    timestamp: '2024-01-13 16:00',
    status: 'failed',
    batchesSynced: 0,
    message: 'Sync failed — No internet connection',
  },
];

export const mockSensors: SensorReading[] = [
  {
    id: 'sensor-001',
    sensorId: 'BLE-T01',
    batteryPercent: 87,
    signalStrength: 92,
    temperature: 4.2,
    humidity: 85,
    timestamp: '14:32:05',
    status: 'normal',
  },
  {
    id: 'sensor-002',
    sensorId: 'BLE-T02',
    batteryPercent: 71,
    signalStrength: 78,
    temperature: 4.8,
    humidity: 83,
    timestamp: '14:32:05',
    status: 'normal',
  },
  {
    id: 'sensor-003',
    sensorId: 'BLE-T03',
    batteryPercent: 55,
    signalStrength: 65,
    temperature: 6.9,
    humidity: 91,
    timestamp: '14:32:04',
    status: 'warning',
  },
  {
    id: 'sensor-004',
    sensorId: 'BLE-T04',
    batteryPercent: 93,
    signalStrength: 88,
    temperature: 3.8,
    humidity: 86,
    timestamp: '14:32:05',
    status: 'normal',
  },
];

export const mockTemperatureHistory: TemperaturePoint[] = [
  { time: '12:30', value: 4.1 },
  { time: '12:45', value: 4.3 },
  { time: '13:00', value: 4.0 },
  { time: '13:15', value: 4.2 },
  { time: '13:30', value: 4.5 },
  { time: '13:45', value: 4.8 },
  { time: '14:00', value: 5.1 },
  { time: '14:15', value: 4.9 },
  { time: '14:30', value: 4.2 },
];

export const mockSensorAlerts: SensorAlert[] = [
  {
    id: 'alert-001',
    sensorId: 'BLE-T03',
    type: 'temperature',
    message: 'Temperature rose to 6.9°C — above 6°C threshold',
    timestamp: '14:28:33',
    severity: 'warning',
  },
  {
    id: 'alert-002',
    sensorId: 'BLE-T03',
    type: 'humidity',
    message: 'Humidity at 91% — above 90% threshold',
    timestamp: '14:30:10',
    severity: 'warning',
  },
  {
    id: 'alert-003',
    sensorId: 'BLE-T02',
    type: 'battery',
    message: 'BLE-T02 battery below 75%',
    timestamp: '11:15:00',
    severity: 'warning',
  },
];

export const mockRouteStops: RouteStop[] = [
  {
    id: 'stop-001',
    name: 'Cameron Highlands',
    time: '08:30',
    status: 'completed',
  },
  {
    id: 'stop-002',
    name: 'Rest Stop Simpang Pulai',
    time: '09:45',
    status: 'completed',
  },
  {
    id: 'stop-003',
    name: 'Gua Musang',
    time: '10:30',
    status: 'current',
  },
  {
    id: 'stop-004',
    name: 'Kluang',
    time: '13:00',
    status: 'upcoming',
  },
  {
    id: 'stop-005',
    name: 'Johor Hub',
    time: '14:15',
    status: 'upcoming',
    isDestination: true,
  },
];

export const mockShipment: Shipment = {
  id: 'ship-001',
  origin: 'Cameron Highlands',
  destination: 'Johor Hub',
  status: 'in_transit',
  etaDisplay: '2h 35min',
  etaMinutes: 155,
  crateCount: 18,
  departureTime: '08:30',
  driverName: 'Ravi Kumar',
  vehiclePlate: 'WGT 1234',
  distanceKm: 342,
  elapsedDisplay: '3h 15min',
  remainingDisplay: '~2h 35min',
  currentSpeedKmh: 87,
  onSchedule: true,
};

export const mockCrateDelivery: CrateDelivery = {
  crateId: 'CRT-4892',
  contents: 'Lettuce Grade A',
  grade: 'A',
  weightKg: 25,
  origin: 'Cameron Highlands Farm',
  farmName: 'Ladang Pak Lah',
  custodyEvents: [
    {
      id: 'evt-001',
      action: 'Harvested & Packed',
      location: 'Ladang Pak Lah, Cameron Highlands',
      timestamp: '2024-01-15 06:00',
      actor: 'Pak Lah (Farmer)',
    },
    {
      id: 'evt-002',
      action: 'AI Graded — Grade A',
      location: 'Packing Station, Cameron Highlands',
      timestamp: '2024-01-15 07:15',
      actor: 'BioLink AI System',
    },
    {
      id: 'evt-003',
      action: 'Loaded onto Vehicle',
      location: 'Cameron Highlands Collection Point',
      timestamp: '2024-01-15 08:20',
      actor: 'Ravi Kumar (Driver)',
    },
    {
      id: 'evt-004',
      action: 'In Transit — Cold Chain Active',
      location: 'En route Johor Hub',
      timestamp: '2024-01-15 08:30',
      actor: 'BLE Sensor BLE-T01',
    },
  ],
};

export const mockTodaySummary = {
  gradedToday: 8,
  pendingSync: 3,
  approved: 7,
  rejected: 1,
};
